# Copyright 2024 Bytedance Ltd. and/or its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import asyncio
import json
import json5
import logging
import os
from abc import ABC, abstractmethod
from typing import Dict, List, Optional

import regex as re
from pydantic import BaseModel

from verl.utils.rollout_trace import rollout_trace_op

logger = logging.getLogger(__file__)
logger.setLevel(os.getenv("VERL_LOGGING_LEVEL", "WARN"))


class FunctionCall(BaseModel):
    arguments: str
    """
    The arguments to call the function with, as generated by the model in JSON
    format. Note that the model does not always generate valid JSON, and may
    hallucinate parameters not defined by your function schema. Validate the
    arguments in your code before calling your function.
    """

    name: str
    """The name of the function to call."""


class ToolParser(ABC):
    _registry: dict[str, type["ToolParser"]] = {}

    def __init__(self, tokenizer) -> None:
        self.tokenizer = tokenizer

    @abstractmethod
    async def extract_tool_calls(self, responses_ids: list[int]) -> tuple[str, list[FunctionCall]]:
        """Extract tool calls from the responses.

        Args:
            responses_ids (List[int]): The ids of the responses.

        Returns:
            Tuple[str, List[FunctionCall]]: Content and extracted tool calls.
        """
        raise NotImplementedError

    @classmethod
    def get_tool_parser(cls, name: str, tokenizer):
        if name not in cls._registry:
            raise ValueError(f"Unknown tool parser: {name}")
        return cls._registry[name](tokenizer)

    @classmethod
    def register(cls, name: str):
        def decorator(subclass: type[ToolParser]) -> type[ToolParser]:
            cls._registry[name] = subclass
            return subclass

        return decorator


@ToolParser.register("hermes")
class HermesToolParser(ToolParser):
    """Adapted from https://github.com/vllm-project/vllm/blob/v0.9.1/vllm/entrypoints/openai/tool_parsers/hermes_tool_parser.py"""

    def __init__(self, tokenizer) -> None:
        super().__init__(tokenizer)

        self.tool_call_start_token: str = "<tool_call>"
        self.tool_call_end_token: str = "</tool_call>"
        self.tool_call_regex = re.compile(r"<tool_call>(.*?)</tool_call>", re.DOTALL)
        self.tool_args = {
            'data_cleaning': ["dataset_path", "task"],
            'feature_engineering': ["dataset_path", "task"],
            'model_development': ["task"],
            'visualization': ["task"],
            'review': ["task", "solution"],
            'bash': ["code"],
            'sql': ["code", "file_path", "output_file"],
            'python': ["code", "file_path"],
            'debugging': ["task", "code"]
        }

    def extract_tool_args(self, text: str, tool_args: Dict[str, List[str]]) -> Optional[str]:
        # 1. 确认工具
        m = re.search(r'"name"\s*:\s*"([^"]+)"', text)
        if not m or m.group(1) not in tool_args:
            return None, None
        tool, need = m.group(1), tool_args[m.group(1)]

        # 2. 直接抓 arguments 后的全部内容（不含 "arguments": 字样）
        m = re.search(r'"arguments"\s*:\s*(.+)', text, flags=re.S)
        if not m:
            return None, None
        inner = m.group(1).strip()

        # 3. 去掉最外层 {}
        if inner.startswith('{') and inner.endswith('}}'):
            inner = inner[1:-2].strip()
        else:
            return None, None
    
        # 4. 只有一个参数：整块拿走，直接剥皮
        if len(need) == 1:
            if f"\"{need[0]}\": " in inner:
                raw = inner.replace(f"\"{need[0]}\": ", "")
            else:
                raw = inner

            # 去首尾引号/逗号/空格
            raw = raw.strip().strip(',"').strip()
            if raw.startswith('"'):
                raw = raw[1:]
            if raw.endswith('"'):
                raw = raw[:-1]

            # raw = raw.encode().decode("unicode_escape")
            return tool, {need[0]: raw}
    
        # 5. 多参数：按 key 顺序依次切
        res = {}
        for i, key in enumerate(need):
            try:
                next_key = need[i + 1]
                p_right = rf'"{next_key}"\s*:\s*'
            except IndexError:
                p_right = None          # 最后一个 key 用结尾 } 当右边界

            p_left = rf'"{key}"\s*:\s*'
            m_left = re.search(p_left, inner)
            if not m_left:
                return None, None
            start = m_left.end()

            if p_right:                     # 非最后一个
                m_right = re.search(p_right, inner[start:])
                if not m_right:
                    return None, None
                end = m_right.start() + start
            else:                           # 最后一个 key
                end = -1

            raw = inner[start:end].strip().rstrip(',').strip()
            # 统一剥两端引号
            if raw.startswith('"'):
                raw = raw[1:]
            if raw.endswith('"'):
                raw = raw[:-1]
            # raw = raw.encode().decode("unicode_escape")
            res[key] = raw
    
        return tool, res
    
    @rollout_trace_op
    async def extract_tool_calls(self, responses_ids: list[int]) -> tuple[str, list[FunctionCall]]:
        loop = asyncio.get_running_loop()
        text = await loop.run_in_executor(None, self.tokenizer.decode, responses_ids)
        if self.tool_call_start_token not in text or self.tool_call_end_token not in text:
            return text, []

        matches = self.tool_call_regex.findall(text)
        function_calls = []
        for match in matches:
            try:
                function_call = json5.loads(match)
                name, arguments = function_call["name"], function_call["arguments"]
                # print(f"name: {name}, arguments: {arguments}")
                function_calls.append(FunctionCall(name=name, arguments=json.dumps(arguments, ensure_ascii=False)))
            except Exception as e:
                name, arguments = self.extract_tool_args(match, self.tool_args)
                if name is None or arguments is None:
                    logger.error(f"Failed to decode tool call: {e}")
                    continue
                function_calls.append(FunctionCall(name=name, arguments=json.dumps(arguments, ensure_ascii=False)))

        # remaing text exclude tool call tokens
        content = self.tool_call_regex.sub("", text)

        return content, function_calls
